### PR TITLE
Updated readme to include myself as contributor

### PR DESCRIPTION
**Pull request by jabracadabrah**
Added section to readme.

### CODE REVIEW

**Comment by phitoduck** [comment]
Yaaaay! Thanks for doing this ticket. I clicked "request reviews" so other contributors can have a chance to see a PR... we have a lot of people we need to get on GitHub still

**Comment by ElSnoMan** [comment]
Ayyy things are looking good!

**Review by ElSnoMan — APPROVED** [review]

**Review by ir3456 — APPROVED** [review]
Looks good to me!

**Comment by phitoduck** [comment]
@jabracadabrah I put your change in a different PR because I'm messing with a new tool to credit contributors :D

**Pull request closed without merging**
